"use server";
import bcrypt from "bcryptjs";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import fs from "fs/promises";
import path from "path";
import prisma from "@/lib/db";
import { createAdminSession, clearAdminSession } from "@/lib/auth";
import { requirePermission, writeAuditLog } from "@/lib/admin";
import { PERMISSION_GROUPS, ALL_PERMISSION_KEYS } from "@/lib/permissions";
import { sanitizeRichText } from "@/lib/richtext";
import { AdminRole, ContentStatus, LeadStatus, ModerationStatus } from "@prisma/client";
import { rateLimit } from "@/lib/rate-limit";

function str(fd: FormData, key: string) { return String(fd.get(key) ?? "").trim(); }
function bool(fd: FormData, key: string) { return fd.get(key) === "on" || fd.get(key) === "true"; }
function num(fd: FormData, key: string, fallback = 0) { const n = Number(str(fd, key)); return Number.isFinite(n) ? n : fallback; }
function slugify(v: string) { return v.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 100); }

export async function loginAction(fd: FormData) {
  const email = str(fd, "email").toLowerCase(); const password = str(fd, "password");
  if (!rateLimit(`admin-login:${email || "unknown"}`, 8, 15 * 60 * 1000).allowed) redirect("/admin/login?error=1");
  const admin = await prisma.adminUser.findUnique({ where: { email } });
  const fallbackHash = "$2a$12$C6UzMDM.H6dfI/f/IKcEe.5JxQ5z5Yf6kQ8ZQW9xK5qj1G8gV8eQe";
  const validPassword = await bcrypt.compare(password, admin?.passwordHash || fallbackHash);
  if (!admin || !admin.isActive || !validPassword) redirect("/admin/login?error=1");
  await createAdminSession(admin.id); await writeAuditLog({ adminUserId: admin.id, action: "LOGIN", resource: "AdminUser", resourceId: admin.id, summary: `${admin.name} logged in` });
  redirect("/admin");
}
export async function logoutAction() { const admin = await (await import("@/lib/auth")).getAuthenticatedAdmin(); if (admin) await writeAuditLog({ adminUserId: admin.id, action: "LOGOUT", resource: "AdminUser", resourceId: admin.id, summary: `${admin.name} logged out` }); await clearAdminSession(); redirect("/admin/login"); }

export async function updateLead(fd: FormData) {
  const admin = await requirePermission("LEADS_EDIT"); const id = str(fd, "id"); const status = str(fd, "status") as LeadStatus; const notes = str(fd, "notes");
  await prisma.contactSubmission.update({ where: { id }, data: { status, notes: notes || null } });
  await writeAuditLog({ adminUserId: admin.id, action: "STATUS_CHANGE", resource: "Lead", resourceId: id, summary: `Updated lead status to ${status}` }); revalidatePath("/admin/leads");
}

export async function saveBlog(fd: FormData) {
  const id = str(fd, "id"); const admin = await requirePermission(id ? "BLOG_EDIT" : "BLOG_CREATE");
  const title = str(fd, "title"); const slug = slugify(str(fd, "slug") || title); const status: ContentStatus = bool(fd, "publishNow") ? "PUBLISHED" : "DRAFT";
  const data = { title, slug, excerpt: str(fd, "excerpt"), content: sanitizeRichText(str(fd, "content")), coverImage: str(fd, "coverImage"), category: str(fd, "category"), author: str(fd, "author") || "EduYatra Team", status, featured: bool(fd, "featured"), seoTitle: str(fd, "seoTitle") || null, seoDescription: str(fd, "seoDescription") || null, publishedAt: status === "PUBLISHED" ? new Date() : null };
  const blog = id ? await prisma.blog.update({ where: { id }, data }) : await prisma.blog.create({ data });
  await writeAuditLog({ adminUserId: admin.id, action: id ? "UPDATE" : "CREATE", resource: "Blog", resourceId: blog.id, summary: `${id ? "Updated" : "Created"} blog: ${title}` }); revalidatePath("/admin/blogs"); revalidatePath("/blogs");
}
export async function deleteBlog(fd: FormData) { const admin = await requirePermission("BLOG_DELETE"); const id = str(fd, "id"); await prisma.blog.delete({ where: { id } }); await writeAuditLog({ adminUserId: admin.id, action: "DELETE", resource: "Blog", resourceId: id, summary: "Deleted blog" }); revalidatePath("/admin/blogs"); }

export async function saveFaq(fd: FormData) {
  const id = str(fd, "id"); const admin = await requirePermission(id ? "FAQ_EDIT" : "FAQ_CREATE"); const data = { question: str(fd, "question"), answer: sanitizeRichText(str(fd, "answer")), category: str(fd, "category"), isPublished: bool(fd, "isPublished"), sortOrder: num(fd, "sortOrder") };
  const row = id ? await prisma.fAQ.update({ where: { id }, data }) : await prisma.fAQ.create({ data }); await writeAuditLog({ adminUserId: admin.id, action: id ? "UPDATE" : "CREATE", resource: "FAQ", resourceId: row.id, summary: `${id ? "Updated" : "Created"} FAQ` }); revalidatePath("/admin/faqs"); revalidatePath("/faq");
}
export async function deleteFaq(fd: FormData) { const admin = await requirePermission("FAQ_DELETE"); const id = str(fd, "id"); await prisma.fAQ.delete({ where: { id } }); await writeAuditLog({ adminUserId: admin.id, action: "DELETE", resource: "FAQ", resourceId: id, summary: "Deleted FAQ" }); revalidatePath("/admin/faqs"); }

export async function saveTestimonial(fd: FormData) {
  const id = str(fd, "id"); const admin = await requirePermission(id ? "TESTIMONIAL_EDIT" : "TESTIMONIAL_CREATE"); const data = { name: str(fd, "name"), photo: str(fd, "photo") || null, testType: str(fd, "testType"), score: str(fd, "score"), reading: num(fd, "reading") || null, listening: num(fd, "listening") || null, writing: num(fd, "writing") || null, speaking: num(fd, "speaking") || null, destination: str(fd, "destination") || null, university: str(fd, "university") || null, course: str(fd, "course") || null, content: str(fd, "content"), isPublished: bool(fd, "isPublished"), isFeatured: bool(fd, "isFeatured"), sortOrder: num(fd, "sortOrder") };
  const row = id ? await prisma.testimonial.update({ where: { id }, data }) : await prisma.testimonial.create({ data }); await writeAuditLog({ adminUserId: admin.id, action: id ? "UPDATE" : "CREATE", resource: "Testimonial", resourceId: row.id, summary: `${id ? "Updated" : "Created"} testimonial` }); revalidatePath("/admin/testimonials"); revalidatePath("/");
}
export async function deleteTestimonial(fd: FormData) { const admin = await requirePermission("TESTIMONIAL_DELETE"); const id = str(fd, "id"); await prisma.testimonial.delete({ where: { id } }); await writeAuditLog({ adminUserId: admin.id, action: "DELETE", resource: "Testimonial", resourceId: id, summary: "Deleted testimonial" }); revalidatePath("/admin/testimonials"); }

export async function moderateQuestion(fd: FormData) { const admin = await requirePermission("COMMUNITY_MODERATE"); const id = str(fd, "id"); const status = str(fd, "status") as ModerationStatus; await prisma.communityQuestion.update({ where: { id }, data: { status } }); await writeAuditLog({ adminUserId: admin.id, action: "STATUS_CHANGE", resource: "CommunityQuestion", resourceId: id, summary: `Question marked ${status}` }); revalidatePath("/admin/community"); revalidatePath("/community"); }
export async function answerQuestion(fd: FormData) { const admin = await requirePermission("COMMUNITY_ANSWER"); const questionId = str(fd, "questionId"); const content = str(fd, "content"); const row = await prisma.communityAnswer.create({ data: { questionId, name: "EduYatra Team", email: admin.email, content: sanitizeRichText(content), isStaff: true, status: "APPROVED" } }); await writeAuditLog({ adminUserId: admin.id, action: "CREATE", resource: "CommunityAnswer", resourceId: row.id, summary: "Answered a community question as EduYatra Team" }); revalidatePath("/admin/community"); revalidatePath("/community"); }
export async function moderateAnswer(fd: FormData) { const admin = await requirePermission("COMMUNITY_MODERATE"); const id = str(fd, "id"); const status = str(fd, "status") as ModerationStatus; await prisma.communityAnswer.update({ where: { id }, data: { status } }); await writeAuditLog({ adminUserId: admin.id, action: "STATUS_CHANGE", resource: "CommunityAnswer", resourceId: id, summary: `Answer marked ${status}` }); revalidatePath("/admin/community"); }

export async function saveCourse(fd: FormData) { const id = str(fd, "id"); const admin = await requirePermission(id ? "COURSE_EDIT" : "COURSE_CREATE"); const name = str(fd, "name"); const row = id ? await prisma.course.update({ where: { id }, data: { name, slug: slugify(str(fd, "slug") || name), shortName: str(fd, "shortName") || null, description: str(fd, "description"), mode: str(fd, "mode") || "Online Classes", availability: str(fd, "availability") || "Multiple batches available", isPublished: bool(fd, "isPublished"), sortOrder: num(fd, "sortOrder") } }) : await prisma.course.create({ data: { name, slug: slugify(str(fd, "slug") || name), shortName: str(fd, "shortName") || null, description: str(fd, "description"), mode: str(fd, "mode") || "Online Classes", availability: str(fd, "availability") || "Multiple batches available", isPublished: bool(fd, "isPublished"), sortOrder: num(fd, "sortOrder") } }); await writeAuditLog({ adminUserId: admin.id, action: id ? "UPDATE" : "CREATE", resource: "Course", resourceId: row.id, summary: `${id ? "Updated" : "Created"} course: ${name}` }); revalidatePath("/admin/courses"); }
export async function saveCoursePackage(fd: FormData) { const id = str(fd, "id"); const admin = await requirePermission(id ? "COURSE_EDIT" : "COURSE_CREATE"); const data = { courseId: str(fd, "courseId"), name: str(fd, "name"), price: num(fd, "price"), description: str(fd, "description"), isPublished: bool(fd, "isPublished"), sortOrder: num(fd, "sortOrder") }; const row = id ? await prisma.coursePackage.update({ where: { id }, data }) : await prisma.coursePackage.create({ data }); await writeAuditLog({ adminUserId: admin.id, action: id ? "UPDATE" : "CREATE", resource: "CoursePackage", resourceId: row.id, summary: `${id ? "Updated" : "Created"} course package` }); revalidatePath("/admin/courses"); }
export async function deleteCoursePackage(fd: FormData) { const admin = await requirePermission("COURSE_DELETE"); const id = str(fd, "id"); await prisma.coursePackage.delete({ where: { id } }); await writeAuditLog({ adminUserId: admin.id, action: "DELETE", resource: "CoursePackage", resourceId: id, summary: "Deleted course package" }); revalidatePath("/admin/courses"); }

export async function saveTestBooking(fd: FormData) { const id = str(fd, "id"); const admin = await requirePermission(id ? "TEST_BOOKING_EDIT" : "TEST_BOOKING_CREATE"); const name = str(fd, "name"); const data = { name, slug: slugify(str(fd, "slug") || name), description: str(fd, "description") || null, whatsappMessage: str(fd, "whatsappMessage"), isPublished: bool(fd, "isPublished"), sortOrder: num(fd, "sortOrder") }; const row = id ? await prisma.testBookingService.update({ where: { id }, data }) : await prisma.testBookingService.create({ data }); await writeAuditLog({ adminUserId: admin.id, action: id ? "UPDATE" : "CREATE", resource: "TestBookingService", resourceId: row.id, summary: `${id ? "Updated" : "Created"} test booking service` }); revalidatePath("/admin/test-booking"); }
export async function deleteTestBooking(fd: FormData) { const admin = await requirePermission("TEST_BOOKING_DELETE"); const id = str(fd, "id"); await prisma.testBookingService.delete({ where: { id } }); await writeAuditLog({ adminUserId: admin.id, action: "DELETE", resource: "TestBookingService", resourceId: id, summary: "Deleted test booking service" }); revalidatePath("/admin/test-booking"); }

export async function saveCountry(fd: FormData) { const id = str(fd, "id"); const admin = await requirePermission(id ? "COUNTRY_EDIT" : "COUNTRY_CREATE"); const name = str(fd, "name"); const data = { name, slug: slugify(str(fd, "slug") || name), heroImage: str(fd, "heroImage") || null, intro: str(fd, "intro"), ctaLabel: str(fd, "ctaLabel") || "Talk to EduYatra", isPublished: bool(fd, "isPublished"), isFeatured: bool(fd, "isFeatured"), sortOrder: num(fd, "sortOrder") }; const row = id ? await prisma.country.update({ where: { id }, data }) : await prisma.country.create({ data }); await writeAuditLog({ adminUserId: admin.id, action: id ? "UPDATE" : "CREATE", resource: "Country", resourceId: row.id, summary: `${id ? "Updated" : "Created"} country: ${name}` }); revalidatePath("/admin/countries"); }
export async function saveCountrySection(fd: FormData) { const admin = await requirePermission("COUNTRY_EDIT"); const id = str(fd, "id"); const data = { countryId: str(fd, "countryId"), heading: str(fd, "heading"), content: sanitizeRichText(str(fd, "content")), sortOrder: num(fd, "sortOrder"), isPublished: bool(fd, "isPublished") }; const row = id ? await prisma.countrySection.update({ where: { id }, data }) : await prisma.countrySection.create({ data }); await writeAuditLog({ adminUserId: admin.id, action: id ? "UPDATE" : "CREATE", resource: "CountrySection", resourceId: row.id, summary: `${id ? "Updated" : "Created"} country section` }); revalidatePath("/admin/countries"); }

export async function savePage(fd: FormData) { const id = str(fd, "id"); const admin = await requirePermission("PAGE_EDIT"); const title = str(fd, "title"); const data = { title, slug: slugify(str(fd, "slug") || title), heroTitle: str(fd, "heroTitle") || null, heroSubtitle: str(fd, "heroSubtitle") || null, heroImage: str(fd, "heroImage") || null, content: sanitizeRichText(str(fd, "content")), status: str(fd, "status") as ContentStatus, seoTitle: str(fd, "seoTitle") || null, seoDescription: str(fd, "seoDescription") || null }; const row = id ? await prisma.page.update({ where: { id }, data }) : await prisma.page.create({ data }); await writeAuditLog({ adminUserId: admin.id, action: id ? "UPDATE" : "CREATE", resource: "Page", resourceId: row.id, summary: `${id ? "Updated" : "Created"} page: ${title}` }); revalidatePath("/admin/pages"); }

export async function saveSettings(fd: FormData) { const admin = await requirePermission("SETTINGS_EDIT"); const entries = Array.from(fd.entries()).filter(([k]) => k.startsWith("setting_")); for (const [key, value] of entries) { const settingKey = key.replace("setting_", ""); await prisma.siteSetting.upsert({ where: { key: settingKey }, update: { value: String(value) }, create: { key: settingKey, value: String(value) } }); } await writeAuditLog({ adminUserId: admin.id, action: "UPDATE", resource: "SiteSetting", summary: "Updated site settings" }); revalidatePath("/admin/settings"); }

export async function saveAdmin(fd: FormData) { const id = str(fd, "id"); const current = id ? await requirePermission("ADMIN_EDIT") : await requirePermission("ADMIN_CREATE"); const name = str(fd, "name"); const email = str(fd, "email").toLowerCase(); const role = str(fd, "role") as AdminRole; const password = str(fd, "password"); if (role === "SUPER_ADMIN" && current.role !== AdminRole.SUPER_ADMIN) throw new Error("FORBIDDEN"); let row; if (id) { row = await prisma.adminUser.update({ where: { id }, data: { name, email, role, ...(password ? { passwordHash: await bcrypt.hash(password, 12) } : {}) } }); } else { if (!password) throw new Error("Password required for new admin"); row = await prisma.adminUser.create({ data: { name, email, role, passwordHash: await bcrypt.hash(password, 12) } }); } const selected = fd.getAll("permissions").map(String).filter(k => ALL_PERMISSION_KEYS.includes(k as any)); if (current.role === AdminRole.SUPER_ADMIN && role === AdminRole.ADMIN) { await prisma.adminPermission.deleteMany({ where: { adminUserId: row.id } }); if (selected.length) { const permissions = await prisma.permission.findMany({ where: { key: { in: selected } } }); await prisma.adminPermission.createMany({ data: permissions.map(p => ({ adminUserId: row.id, permissionId: p.id })) }); } } await writeAuditLog({ adminUserId: current.id, action: id ? "UPDATE" : "CREATE", resource: "AdminUser", resourceId: row.id, summary: `${id ? "Updated" : "Created"} admin ${name}` }); revalidatePath("/admin/admins"); }
export async function toggleAdmin(fd: FormData) { const admin = await requirePermission("ADMIN_DEACTIVATE"); const id = str(fd, "id"); const target = await prisma.adminUser.findUnique({ where: { id } }); if (!target || target.role === "SUPER_ADMIN" || target.id === admin.id) throw new Error("Cannot deactivate a superadmin or your own account"); await prisma.adminUser.update({ where: { id }, data: { isActive: !target.isActive } }); await writeAuditLog({ adminUserId: admin.id, action: target.isActive ? "DEACTIVATE" : "ACTIVATE", resource: "AdminUser", resourceId: id, summary: `${target.isActive ? "Deactivated" : "Activated"} admin ${target.name}` }); revalidatePath("/admin/admins"); }

export async function removeSubscriber(fd: FormData) { const admin = await requirePermission("ANNOUNCEMENTS_MANAGE"); const id = str(fd, "id"); const row = await prisma.announcementSubscriber.update({ where: { id }, data: { isActive: false } }); await writeAuditLog({ adminUserId: admin.id, action: "DEACTIVATE", resource: "AnnouncementSubscriber", resourceId: id, summary: `Deactivated subscriber ${row.email}` }); revalidatePath("/admin/subscribers"); }

export async function uploadMedia(fd: FormData) { const admin = await requirePermission("MEDIA_UPLOAD"); const file = fd.get("file"); const altText = str(fd, "altText"); if (!(file instanceof File) || file.size === 0) throw new Error("No file selected"); if (!file.type.startsWith("image/")) throw new Error("Only image uploads are supported"); if (file.size > 5 * 1024 * 1024) throw new Error("Image must be 5MB or smaller"); const ext = path.extname(file.name).toLowerCase() || ".bin"; const safeName = `${Date.now()}-${slugify(path.basename(file.name, ext)) || "image"}${ext}`; const dir = path.join(process.cwd(), "public", "uploads"); await fs.mkdir(dir, { recursive: true }); await fs.writeFile(path.join(dir, safeName), Buffer.from(await file.arrayBuffer())); const row = await prisma.mediaAsset.create({ data: { filename: file.name, url: `/uploads/${safeName}`, altText: altText || null, mimeType: file.type, sizeBytes: file.size, uploadedById: admin.id } }); await writeAuditLog({ adminUserId: admin.id, action: "CREATE", resource: "MediaAsset", resourceId: row.id, summary: `Uploaded media ${file.name}` }); revalidatePath("/admin/media"); }
export async function deleteMedia(fd: FormData) { const admin = await requirePermission("MEDIA_DELETE"); const id = str(fd, "id"); const row = await prisma.mediaAsset.findUnique({ where: { id } }); if (row) { const relative = row.url.startsWith("/") ? row.url.slice(1) : row.url; await fs.unlink(path.join(process.cwd(), "public", relative)).catch(() => undefined); await prisma.mediaAsset.delete({ where: { id } }); await writeAuditLog({ adminUserId: admin.id, action: "DELETE", resource: "MediaAsset", resourceId: id, summary: `Deleted media ${row.filename}` }); } revalidatePath("/admin/media"); }

export async function deleteCourse(fd: FormData) { const admin = await requirePermission("COURSE_DELETE"); const id = str(fd, "id"); await prisma.course.delete({ where: { id } }); await writeAuditLog({ adminUserId: admin.id, action: "DELETE", resource: "Course", resourceId: id, summary: "Deleted course" }); revalidatePath("/admin/courses"); }
export async function deleteCountry(fd: FormData) { const admin = await requirePermission("COUNTRY_DELETE"); const id = str(fd, "id"); await prisma.country.delete({ where: { id } }); await writeAuditLog({ adminUserId: admin.id, action: "DELETE", resource: "Country", resourceId: id, summary: "Deleted country" }); revalidatePath("/admin/countries"); }
