import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { ArrowRight, CheckCircle2, Globe2 } from "lucide-react";
import Link from "next/link";
import Image from "next/image";
import prisma from "@/lib/db";
import WhatsAppButton from "@/components/public/WhatsAppButton";
export const dynamic="force-dynamic";
export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> {
  const country = await prisma.country.findFirst({ where: { slug: params.slug, isPublished: true }, select: { name: true, intro: true } });
  if (!country) return {};
  return { title: `Study in ${country.name}`, description: country.intro.slice(0, 155) };
}

export default async function CountryPage({params}:{params:{slug:string}}){const country=await prisma.country.findFirst({where:{slug:params.slug,isPublished:true},include:{sections:{where:{isPublished:true},orderBy:{sortOrder:"asc"}}}});if(!country)return notFound();return <div><section className="relative overflow-hidden bg-gradient-to-br from-brand-navy to-brand-blue text-white">{country.heroImage && <Image src={country.heroImage} alt={country.name} fill sizes="100vw" className="object-cover opacity-20" />}<div className="relative"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="flex max-w-3xl items-start gap-5"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-white/10"><Globe2/></span><div><p className="text-xs font-extrabold uppercase tracking-[0.22em] text-orange-300">Study destination</p><h1 className="mt-2 text-5xl font-black">Study in {country.name}</h1><p className="mt-5 text-lg leading-8 text-white/75">{country.intro}</p><div className="mt-7"><WhatsAppButton label={country.ctaLabel||"Talk to EduYatra"} message={`Hello EduYatra, I would like guidance about studying in ${country.name}.`}/></div></div></div></div></div></section><section className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8"><div className="space-y-6">{country.sections.length?country.sections.map(section=><article key={section.id} className="rounded-[1.5rem] border border-slate-200 bg-white p-7 shadow-sm"><h2 className="text-2xl font-black text-brand-navy">{section.heading}</h2><div className="mt-4 leading-7 text-slate-600 [&_a]:text-brand-blue [&_a]:underline [&_h2]:mb-3 [&_h2]:text-xl [&_h2]:font-black [&_li]:ml-5 [&_li]:list-disc" dangerouslySetInnerHTML={{__html:section.content}}/></article>):<div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-8 text-center"><h2 className="text-xl font-black text-brand-navy">Country guidance is being prepared.</h2><p className="mt-2 text-sm text-slate-600">Contact EduYatra for a conversation about {country.name}.</p><div className="mt-5"><WhatsAppButton label="Ask about this destination" message={`Hello EduYatra, I would like guidance about studying in ${country.name}.`}/></div></div>}</div><div className="mt-10 flex flex-wrap gap-3"><Link href="/study-abroad" className="inline-flex items-center gap-2 rounded-full border border-slate-200 px-5 py-3 text-sm font-extrabold text-brand-navy">All destinations <ArrowRight className="h-4 w-4"/></Link><Link href="/contact" className="inline-flex items-center gap-2 rounded-full bg-brand-navy px-5 py-3 text-sm font-extrabold text-white"><CheckCircle2 className="h-4 w-4"/> Start a consultation</Link></div></section></div>}
