export const EDUYATRA_CONFIG = {
  name: "EduYatra Nepal",
  tagline: "Your Journey to Global Success",
  address: "New Baneshwor, Kathmandu, Nepal",
  phone: "+9779811802843",
  phoneDisplay: "+977 9811802843",
  phoneRaw: "9779811802843",
  email: "eduyatra.np@gmail.com",
  officeHours: "Weekdays: 6:00 AM – 10:00 PM",
  socials: {
    instagram: "https://www.instagram.com/eduyatranepal",
    tiktok: "https://www.tiktok.com/@eduyatra.nepal",
    facebook: "https://www.facebook.com/share/1bWhdJba7p/",
    whatsapp: "https://wa.me/9779811802843",
  },
  courses: {
    pte: {
      name: "PTE Academic",
      mode: "Online Classes",
      availability: "Multiple batches available",
      tiers: [
        { name: "Basic", fee: "Rs. 1,000", description: "Classes only" },
        { name: "Advanced", fee: "Rs. 2,500", description: "Classes + PTE practice software" },
        { name: "Premium", fee: "Rs. 3,500", description: "Classes + PTE practice software + class recordings" },
      ],
      features: ["One-on-one consultation", "Small batches", "Nepali-friendly classes"],
      classMessage: "Hello EduYatra, I would like to inquire about PTE online classes.",
      testMessage: "Hello EduYatra, I would like to book a PTE test.",
    },
    duolingo: {
      name: "Duolingo English Test",
      mode: "Online Classes",
      availability: "Multiple batches available",
      fee: "Rs. 750",
      description: "Full coverage of the Duolingo English Test syllabus and all sections.",
      features: ["One-on-one consultation", "Small batches", "Nepali-friendly classes"],
      classMessage: "Hello EduYatra, I would like to inquire about Duolingo online classes.",
      testMessage: "Hello EduYatra, I would like to book a Duolingo test.",
    },
    ielts: {
      name: "IELTS",
      mode: "Online Classes",
      availability: "Multiple batches available",
      tiers: [
        { name: "Basic", fee: "Rs. 1,500", description: "Classes only" },
        { name: "Advanced", fee: "Rs. 2,500", description: "Classes + IELTS practice software" },
        { name: "Premium", fee: "Rs. 3,500", description: "Classes + IELTS practice software + class recordings" },
      ],
      features: ["One-on-one consultation", "Small batches", "Nepali-friendly classes"],
      classMessage: "Hello EduYatra, I would like to inquire about IELTS online classes.",
      testMessage: "Hello EduYatra, I would like to book an IELTS test.",
    },
  },
  testBooking: [
    { name: "PTE", message: "Hello EduYatra, I would like to book a PTE test." },
    { name: "Duolingo", message: "Hello EduYatra, I would like to book a Duolingo test." },
    { name: "IELTS", message: "Hello EduYatra, I would like to book an IELTS test." },
    { name: "GRE", message: "Hello EduYatra, I would like to book a GRE test." },
    { name: "SAT", message: "Hello EduYatra, I would like to book an SAT test." },
    { name: "TOEFL", message: "Hello EduYatra, I would like to book a TOEFL test." },
  ],
  destinations: [
    "Australia",
    "United Kingdom",
    "United States",
    "New Zealand",
    "South Korea",
    "Japan",
    "Europe",
    "India",
    "Bangladesh",
  ],
};

export type CourseKey = keyof typeof EDUYATRA_CONFIG.courses;
