import Link from "next/link";
import Image from "next/image";
import { ArrowRight, BookOpen, CheckCircle2, Globe2, GraduationCap, ShieldCheck, Sparkles } from "lucide-react";
import prisma from "@/lib/db";
import SectionHeading from "@/components/public/SectionHeading";
import CourseCard from "@/components/public/CourseCard";
import WhatsAppButton from "@/components/public/WhatsAppButton";
import TestBookingGrid from "@/components/public/TestBookingGrid";
import NewsletterForm from "@/components/public/NewsletterForm";
export const dynamic="force-dynamic";
export default async function HomePage(){
 const [courses,services,testimonials,countries,blogs,countryCount]=await Promise.all([
  prisma.course.findMany({where:{isPublished:true},include:{features:{orderBy:{sortOrder:"asc"}},packages:{where:{isPublished:true},orderBy:{sortOrder:"asc"}}},orderBy:{sortOrder:"asc"}}),
  prisma.testBookingService.findMany({where:{isPublished:true},orderBy:{sortOrder:"asc"}}),
  prisma.testimonial.findMany({where:{isPublished:true},orderBy:{sortOrder:"asc"},take:3}),
  prisma.country.findMany({where:{isPublished:true},orderBy:{sortOrder:"asc"},take:6}),
  prisma.blog.findMany({where:{status:"PUBLISHED"},orderBy:{publishedAt:"desc"},take:3}),
  prisma.country.count({where:{isPublished:true}}),
 ]);
 return <div>
  <section className="relative overflow-hidden bg-[radial-gradient(circle_at_80%_20%,rgba(0,132,209,.16),transparent_32%),linear-gradient(135deg,#f8fbff_0%,#fff7f2_100%)]"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-16 sm:px-6 sm:py-20 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-24"><div><div className="inline-flex items-center gap-2 rounded-full border border-brand-blue/15 bg-white/80 px-3 py-2 text-xs font-extrabold text-brand-navy shadow-sm"><Sparkles className="h-3.5 w-3.5 text-brand-orange"/> Education guidance, preparation & global pathways</div><h1 className="mt-6 max-w-3xl text-5xl font-black leading-[1.02] tracking-tight text-brand-navy sm:text-6xl lg:text-7xl">Turn your study-abroad plan into a <span className="text-brand-orange">clear next step.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-600 sm:text-lg">Online PTE, Duolingo and IELTS preparation, test-date booking, destination guidance and student support — designed around the way Nepali students actually plan their journey.</p><div className="mt-8 flex flex-wrap gap-3"><WhatsAppButton label="Talk to EduYatra"/><Link href="/test-preparation/pte-academic" className="inline-flex items-center gap-2 rounded-full border border-brand-navy bg-white px-5 py-3 text-sm font-extrabold text-brand-navy">Explore preparation <ArrowRight className="h-4 w-4"/></Link></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs font-bold text-slate-500"><span><CheckCircle2 className="mr-1 inline h-4 w-4 text-brand-blue"/>Online classes</span><span><CheckCircle2 className="mr-1 inline h-4 w-4 text-brand-blue"/>Multiple batches</span><span><CheckCircle2 className="mr-1 inline h-4 w-4 text-brand-blue"/>Small batches</span></div></div><div className="relative"><div className="absolute -inset-4 rounded-[2.5rem] bg-brand-blue/10 blur-2xl"/><div className="relative overflow-hidden rounded-[2.25rem] border border-white bg-white p-3 shadow-2xl"><Image src="/brand/logo.png" alt="EduYatra Nepal" width={700} height={700} className="mx-auto aspect-square rounded-[1.75rem] object-contain bg-slate-50 p-8"/><div className="absolute bottom-7 left-7 right-7 rounded-2xl border border-white/70 bg-white/90 p-4 shadow-lg backdrop-blur"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-slate-500">Start with the right exam</p><p className="mt-1 font-black text-brand-navy">PTE · IELTS · Duolingo</p></div><BookOpen className="h-6 w-6 text-brand-orange"/></div></div></div></div></div></section>
  <section className="border-y border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-slate-200 px-4 py-5 sm:grid-cols-4 sm:px-6 lg:px-8"><div className="px-4 text-center"><p className="text-2xl font-black text-brand-navy">{courses.length}</p><p className="text-xs font-bold text-slate-500">Online prep tracks</p></div><div className="px-4 text-center"><p className="text-2xl font-black text-brand-navy">{services.length}</p><p className="text-xs font-bold text-slate-500">Test booking options</p></div><div className="px-4 text-center"><p className="text-2xl font-black text-brand-navy">{countryCount}</p><p className="text-xs font-bold text-slate-500">Study destinations</p></div><div className="px-4 text-center"><p className="text-2xl font-black text-brand-navy">1:1</p><p className="text-xs font-bold text-slate-500">Consultation support</p></div></div></section>
  <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><SectionHeading eyebrow="Online preparation" title="Choose the preparation track that fits your plan" description="Transparent course options, online delivery and practical support. Class schedules stay flexible because batches can be managed from the admin portal."/><div className="mt-10 grid gap-6 lg:grid-cols-3">{courses.map(c=><CourseCard key={c.id} course={c}/>)}</div></section>
  <section className="bg-slate-100/70 py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><SectionHeading align="left" eyebrow="Test booking" title="Need a test date? Start on WhatsApp" description="EduYatra can help you with PTE, Duolingo, IELTS, GRE, SAT and TOEFL test booking enquiries."/><Link href="/test-booking" className="shrink-0 text-sm font-extrabold text-brand-orange">See all test options →</Link></div><div className="mt-10"><TestBookingGrid services={services}/></div></div></section>
  <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><SectionHeading eyebrow="Study abroad" title="Plan beyond the test" description="From choosing a destination and university to preparing for the next stage of your international student journey, EduYatra brings the pieces together."/><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{countries.map(country=><Link key={country.id} href={`/study-abroad/${country.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-center justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-blue/10 text-brand-blue"><Globe2 className="h-5 w-5"/></span><ArrowRight className="h-4 w-4 text-slate-400 transition group-hover:translate-x-1 group-hover:text-brand-orange"/></div><h3 className="mt-5 text-xl font-black text-brand-navy">{country.name}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{country.intro}</p></Link>)}</div><div className="mt-8 text-center"><Link href="/study-abroad" className="inline-flex items-center gap-2 rounded-full bg-brand-navy px-5 py-3 text-sm font-extrabold text-white">Explore destinations <ArrowRight className="h-4 w-4"/></Link></div></section>
  <section className="bg-brand-navy py-20 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-2 lg:px-8"><div><p className="text-xs font-extrabold uppercase tracking-[0.22em] text-orange-300">Why EduYatra</p><h2 className="mt-3 text-4xl font-black">A connected journey, not a pile of disconnected services.</h2><p className="mt-5 max-w-xl leading-7 text-white/70">Prepare for the exam, understand your options, ask questions, and move toward your next academic step with one consistent support team.</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white/10 p-5"><GraduationCap className="h-6 w-6 text-orange-300"/><h3 className="mt-4 font-extrabold">Student-first guidance</h3><p className="mt-2 text-sm leading-6 text-white/65">Nepali-friendly explanations and practical one-on-one support.</p></div><div className="rounded-2xl bg-white/10 p-5"><ShieldCheck className="h-6 w-6 text-orange-300"/><h3 className="mt-4 font-extrabold">Clear information</h3><p className="mt-2 text-sm leading-6 text-white/65">Organised courses, destinations, FAQs and resources.</p></div><div className="rounded-2xl bg-white/10 p-5"><BookOpen className="h-6 w-6 text-orange-300"/><h3 className="mt-4 font-extrabold">Learn online</h3><p className="mt-2 text-sm leading-6 text-white/65">Multiple online batches without forcing a single timetable on every student.</p></div><div className="rounded-2xl bg-white/10 p-5"><Globe2 className="h-6 w-6 text-orange-300"/><h3 className="mt-4 font-extrabold">Global pathways</h3><p className="mt-2 text-sm leading-6 text-white/65">Explore destinations across Australia, UK, USA, NZ, Asia and Europe.</p></div></div></div></section>
  {testimonials.length>0&&<section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><SectionHeading eyebrow="Student outcomes" title="Real student stories and scores" description="Published testimonials are managed from the EduYatra admin portal."/><div className="mt-10 grid gap-6 md:grid-cols-3">{testimonials.map(t=><article key={t.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="relative aspect-[4/3] bg-slate-100">{t.photo?<Image src={t.photo} alt={t.name} fill className="object-cover"/>:<div className="flex h-full items-center justify-center text-slate-400">Student photo</div>}</div><div className="p-5"><div className="flex items-center justify-between gap-3"><h3 className="font-black text-brand-navy">{t.name}</h3><span className="rounded-full bg-orange-50 px-3 py-1 text-xs font-black text-brand-orange">{t.testType} {t.score}</span></div><p className="mt-3 text-sm leading-6 text-slate-600">“{t.content}”</p>{t.destination&&<p className="mt-4 text-xs font-bold text-slate-500">Destination: {t.destination}</p>}</div></article>)}</div></section>}
  {blogs.length>0&&<section className="bg-slate-100/70 py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex items-end justify-between gap-4"><SectionHeading align="left" eyebrow="Latest insights" title="Useful reads for your next step"/><Link href="/blogs" className="text-sm font-extrabold text-brand-orange">View all →</Link></div><div className="mt-10 grid gap-6 md:grid-cols-3">{blogs.map(b=><Link key={b.id} href={`/blogs/${b.slug}`} className="group rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><span className="text-xs font-extrabold uppercase tracking-widest text-brand-orange">{b.category}</span><h3 className="mt-3 text-xl font-black text-brand-navy group-hover:text-brand-orange">{b.title}</h3><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-500">{b.excerpt}</p><span className="mt-5 inline-flex items-center gap-2 text-xs font-extrabold text-brand-navy">Read guide <ArrowRight className="h-3.5 w-3.5"/></span></Link>)}</div></div></section>}
  <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="rounded-[2rem] bg-gradient-to-r from-orange-50 to-blue-50 p-8 sm:p-10"><div className="grid items-center gap-8 lg:grid-cols-[1fr_1.1fr]"><div><p className="text-xs font-extrabold uppercase tracking-[0.22em] text-brand-orange">Stay updated</p><h2 className="mt-2 text-3xl font-black text-brand-navy">Get useful updates without the noise.</h2><p className="mt-3 text-sm leading-6 text-slate-600">Subscribe for EduYatra announcements, preparation resources and new guidance.</p></div><NewsletterForm/></div></div></section>
 </div>;
}
